// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RedDog.Search.Portal")]
[assembly: AssemblyDescriptionAttribute("A management portal for Azure Search")]
[assembly: AssemblyProductAttribute("RedDog.Search.Portal")]
[assembly: AssemblyVersionAttribute("1.3.0.0")]
[assembly: AssemblyFileVersionAttribute("1.3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.3.0.0";
    }
}
